apiVersion: v1
kind: Service
metadata:
  name: fitmealor-fastapi
spec:
  selector:
    app: fitmealor-fastapi
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fitmealor-nodejs
spec:
  selector:
    app: fitmealor-nodejs
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: fitmealor-frontend
spec:
  selector:
    app: fitmealor-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
